// generated by `sqlx migrate build-script`
fn main() {
    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=migrations");

    // With the (default) `embed-ui` feature, the UI static export is embedded
    // at compile time: require it up front with a clear error, and re-embed
    // whenever it changes.
    if std::env::var_os("CARGO_FEATURE_EMBED_UI").is_some() {
        println!("cargo:rerun-if-changed=out");
        if !std::path::Path::new("out/index.html").exists() {
            panic!(
                "embed-ui: `out/index.html` not found. Run `bun install && bun run build` \
                 to produce the UI static export first, or build with \
                 `--no-default-features` for an API-only server."
            );
        }
    }
}
